all:
	@g++ vec3.h -o vec3.exe
	@g++ Main.cpp -o main.exe
run:
	@g++ vec3.h -o vec3.exe
	@g++ Main.cpp -o main.exe
	@./main.exe
ppm:
	@g++ make_img.cpp -o make_ppm
	@./make_ppm my_file.txt
clean:
	@rm main.exe
	@rm vec3.exe